# PHONY target to ensure "clean" is run as a command and not as a file check.
.PHONY: clean

# clean command definition
clean:
	@echo "Cleaning up..."
	rm -f *_new*                
	rm -f *.snapcoeff           
	rm -f *.snapparam           
	rm -f *.data                
	rm -f *.xyz                 
	rm -f *.log                 
	rm -f *.lammps-data         
	rm -f *.lammps*             
	rm -rf minim_output/        
	@echo "Cleaning completed."
